# Generated by Django 2.2.4 on 2021-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20210826_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
