# Generated by Django 2.2.4 on 2021-08-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_write_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='file',
        ),
    ]
