# Generated by Django 2.2.4 on 2021-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_remove_write_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='write',
            name='upload_files',
        ),
        migrations.AddField(
            model_name='write',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
