# Generated by Django 2.2.4 on 2021-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_auto_20210826_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded Files/'),
        ),
    ]
