# Generated by Django 2.2.4 on 2021-08-26 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score10', models.IntegerField(blank=True, default='0', null=True)),
                ('score11', models.IntegerField(blank=True, default='0', null=True)),
                ('score12', models.IntegerField(blank=True, default='0', null=True)),
                ('score1', models.IntegerField(blank=True, default='0', null=True)),
                ('score2', models.IntegerField(blank=True, default='0', null=True)),
                ('score3', models.IntegerField(blank=True, default='0', null=True)),
                ('score4', models.IntegerField(blank=True, default='0', null=True)),
                ('score5', models.IntegerField(blank=True, default='0', null=True)),
                ('score6', models.IntegerField(blank=True, default='0', null=True)),
                ('score7', models.IntegerField(blank=True, default='0', null=True)),
                ('score8', models.IntegerField(blank=True, default='0', null=True)),
                ('score9', models.IntegerField(blank=True, default='0', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
